export const certificateQuestions = [
  {id:'ca-1',moduleId:'ca',type:'mc',prompt:'Em uma PKI típica, quem emite certificados finais?',options:['A Root CA diretamente em todos os casos','Uma Intermediate CA','O endpoint','O truststore'],correct:'Uma Intermediate CA',explanation:'A Root costuma ficar mais protegida e assina intermediárias.'},
  {id:'ca-2',moduleId:'ca',type:'tf',prompt:'Certificados de CA normalmente possuem a extensão Basic Constraints com CA: TRUE.',options:['Verdadeiro','Falso'],correct:'Verdadeiro',explanation:'Essa extensão indica que o certificado pode atuar como CA.'},
  {id:'ca-3',moduleId:'ca',type:'mc',prompt:'Como uma CA assina um certificado solicitado?',options:['Com a private key da CA','Com a public key do solicitante','Com a private key do solicitante','Com AES'],correct:'Com a private key da CA',explanation:'A assinatura é depois verificada com a public key da CA.'},
  {id:'ca-4',moduleId:'ca',type:'tf',prompt:'Um certificado final normalmente deve ter CA: FALSE.',options:['Verdadeiro','Falso'],correct:'Verdadeiro',explanation:'Ele identifica um endpoint, não uma autoridade emissora.'},
  {id:'chain-1',moduleId:'chain',type:'mc',prompt:'O que o servidor normalmente apresenta no handshake?',options:['Certificado final e intermediárias','A Root e sua private key','Somente a Root','Todas as private keys'],correct:'Certificado final e intermediárias',explanation:'A Root é normalmente um trust anchor já instalado no cliente.'},
  {id:'chain-2',moduleId:'chain',type:'tf',prompt:'Uma cadeia pode conter mais de uma Intermediate CA.',options:['Verdadeiro','Falso'],correct:'Verdadeiro',explanation:'Cadeias podem ter vários níveis entre o certificado final e a Root.'},
  {id:'chain-3',moduleId:'chain',type:'mc',prompt:'Subject e Issuer com nomes compatíveis bastam para estabelecer confiança?',options:['Sim','Não; assinaturas, validade, extensões e trust anchor também importam'],correct:'Não; assinaturas, validade, extensões e trust anchor também importam',explanation:'Nomes ajudam a montar a cadeia, mas a validação é criptográfica e baseada em política.'},
  {id:'chain-4',moduleId:'chain',type:'mc',prompt:'Se uma Intermediate for confiada diretamente, qual papel ela pode assumir?',options:['Session key','Trust anchor','Private key do endpoint','Cipher suite'],correct:'Trust anchor',explanation:'A política local pode encerrar a cadeia em uma intermediária confiada diretamente.'}
];
