export const foundationQuestions = [
  {id:'keys-1',moduleId:'keys',type:'mc',prompt:'Qual informação deve permanecer secreta durante todo o ciclo de vida do certificado?',options:['A chave pública','A chave privada','O certificado final','O nome do emissor'],correct:'A chave privada',explanation:'A chave privada prova posse e nunca deve ser distribuída; certificado e chave pública podem ser compartilhados.'},
  {id:'keys-2',moduleId:'keys',type:'tf',prompt:'Roubar somente o certificado público permite ao invasor autenticar-se como seu titular.',options:['Verdadeiro','Falso'],correct:'Falso',explanation:'A autenticação exige provar a posse da chave privada correspondente.'},
  {id:'keys-3',moduleId:'keys',type:'mc',prompt:'O que um certificado X.509 contém?',options:['A private key e a senha','Public key, identidade, validade, issuer, extensões e assinatura','Apenas o domínio','A session key TLS'],correct:'Public key, identidade, validade, issuer, extensões e assinatura',explanation:'A chave privada não faz parte do certificado.'},
  {id:'keys-4',moduleId:'keys',type:'mc',prompt:'Dois containers guardam a mesma private key. O que muda matematicamente?',options:['A chave','O algoritmo','Nada na chave; muda o empacotamento','A public key deixa de corresponder'],correct:'Nada na chave; muda o empacotamento',explanation:'Reempacotar não gera uma nova chave.'},
  {id:'csr-1',moduleId:'csr',type:'mc',prompt:'O que um CSR carrega e como prova a posse da chave?',options:['Private key assinada pela CA','Public key e dados, assinados com a private key do solicitante','Certificado final e Root','Somente Subject'],correct:'Public key e dados, assinados com a private key do solicitante',explanation:'A assinatura do CSR demonstra posse da chave privada sem enviá-la.'},
  {id:'csr-2',moduleId:'csr',type:'mc',prompt:'De onde keytool -certreq obtém a private key usada para assinar o CSR?',options:['Da CA','Da entry indicada pelo alias no keystore','Do truststore remoto','Do certificado público'],correct:'Da entry indicada pelo alias no keystore',explanation:'O alias aponta para a PrivateKeyEntry criada anteriormente.'},
  {id:'csr-3',moduleId:'csr',type:'order',prompt:'Ordene o fluxo de emissão.',items:['Gerar keypair','Criar CSR','CA assina o certificado','Importar certificate reply'],correct:['Gerar keypair','Criar CSR','CA assina o certificado','Importar certificate reply'],explanation:'O keypair existe antes do CSR; a resposta assinada volta à entry original.'},
  {id:'csr-4',moduleId:'csr',type:'mc',prompt:'O que keytool -genkeypair cria?',options:['Somente um certificado confiável','Um keypair e uma PrivateKeyEntry com certificado inicial','Uma CA pública','Uma session key AES'],correct:'Um keypair e uma PrivateKeyEntry com certificado inicial',explanation:'O comando cria a chave privada, pública e a entry identificada pelo alias.'}
];
