export const storeQuestions = [
  {id:'stores-1',moduleId:'stores',type:'mc',prompt:'O que uma PrivateKeyEntry pode guardar sob um alias?',options:['Private key e certificate chain','Somente Root CA','Apenas senha','Session keys TLS'],correct:'Private key e certificate chain',explanation:'A entry reúne a identidade criptográfica e sua cadeia.'},
  {id:'stores-2',moduleId:'stores',type:'mc',prompt:'O que caracteriza uma TrustedCertificateEntry?',options:['Possui private key','Contém certificado confiável sem private key','É sempre uma Root pública','É uma session key'],correct:'Contém certificado confiável sem private key',explanation:'Ela representa confiança, não identidade com prova de posse.'},
  {id:'stores-3',moduleId:'stores',type:'tf',prompt:'Keystore e truststore descrevem principalmente finalidades, não formatos específicos.',options:['Verdadeiro','Falso'],correct:'Verdadeiro',explanation:'Ambos podem usar formatos como PKCS12; o papel é que difere.'},
  {id:'stores-4',moduleId:'stores',type:'mc',prompt:'Qual é a função de -alias no keytool?',options:['Escolher a entry','Escolher a cipher suite','Definir a CA','Definir o hostname'],correct:'Escolher a entry',explanation:'O alias identifica uma entrada no container.'},
  {id:'stores-5',moduleId:'stores',type:'mc',prompt:'Store password e key password são:',options:['Sempre idênticas por definição','Conceitos distintos','Chaves públicas','Extensões X.509'],correct:'Conceitos distintos',explanation:'Uma protege o container; outra pode proteger a chave privada.'},
  {id:'containers-1',moduleId:'containers',type:'mc',prompt:'Qual container é padronizado e amplamente interoperável?',options:['JKS','PKCS12','PEM apenas','CRT'],correct:'PKCS12',explanation:'PKCS12 é suportado por vários ecossistemas.'},
  {id:'containers-2',moduleId:'containers',type:'mc',prompt:'JKS é melhor descrito como:',options:['Formato tradicional do ecossistema Java','Protocolo TLS','Codificação Base64','Uma CA'],correct:'Formato tradicional do ecossistema Java',explanation:'É um formato histórico de keystore Java.'},
  {id:'containers-3',moduleId:'containers',type:'tf',prompt:'Java moderno pode usar PKCS12 como keystore.',options:['Verdadeiro','Falso'],correct:'Verdadeiro',explanation:'Keystore não é sinônimo de JKS.'},
  {id:'containers-4',moduleId:'containers',type:'mc',prompt:'Qual opção escolhe o tipo do container no keytool?',options:['-alias','-storetype','-keypass','-dname'],correct:'-storetype',explanation:'Ela define, por exemplo, PKCS12 ou JKS.'},
  {id:'containers-5',moduleId:'containers',type:'mc',prompt:'Converter JKS para PKCS12 necessariamente gera uma nova private key?',options:['Sim','Não'],correct:'Não',explanation:'A mesma chave pode ser reempacotada em outro container.'}
];
