export const tlsQuestions = [
  {id:'mtls-1',moduleId:'mtls',type:'mc',prompt:'No TLS comum, quem é normalmente autenticado por certificado?',options:['O servidor','Somente o cliente','Ninguém','A CA offline'],correct:'O servidor',explanation:'O cliente valida a identidade do servidor.'},
  {id:'mtls-2',moduleId:'mtls',type:'mc',prompt:'O que mTLS acrescenta?',options:['Autenticação do cliente por certificado','Autorização automática','HTTP/3','Uma Root no servidor'],correct:'Autenticação do cliente por certificado',explanation:'Ambos os lados apresentam e validam identidade.'},
  {id:'mtls-3',moduleId:'mtls',type:'tf',prompt:'mTLS substitui regras de autorização.',options:['Verdadeiro','Falso'],correct:'Falso',explanation:'Autenticar quem é o cliente não decide o que ele pode fazer.'},
  {id:'mtls-4',moduleId:'mtls',type:'mc',prompt:'Como o servidor pode usar a identidade mTLS?',options:['Vinculá-la a client, aplicação ou conta','Extrair a private key','Ignorar autorização','Gerar HTTP/3'],correct:'Vinculá-la a client, aplicação ou conta',explanation:'O certificado autenticado vira uma identidade aplicável às políticas.'},
  {id:'tls13-1',moduleId:'tls13',type:'mc',prompt:'Qual mecanismo estabelece segredos efêmeros no TLS moderno?',options:['ECDHE','RSA-2048 como session key','Base64','JKS'],correct:'ECDHE',explanation:'ECDHE produz segredos temporários compartilhados.'},
  {id:'tls13-2',moduleId:'tls13',type:'mc',prompt:'Qual benefício central do ECDHE?',options:['Forward secrecy','Autorizar usuários','Converter PEM','Ocultar o certificado'],correct:'Forward secrecy',explanation:'Comprometer a chave de longo prazo depois não revela sessões passadas capturadas.'},
  {id:'tls13-3',moduleId:'tls13',type:'tf',prompt:'RSA-2048 informa o tamanho da session key simétrica.',options:['Verdadeiro','Falso'],correct:'Falso',explanation:'Refere-se ao tamanho da chave RSA, não da chave AES/ChaCha da sessão.'},
  {id:'tls13-4',moduleId:'tls13',type:'mc',prompt:'Qual conjunto contém apenas cifras simétricas modernas?',options:['AES-128-GCM, AES-256-GCM e ChaCha20-Poly1305','RSA, CSR e PEM','JKS, DER e AES','ECDHE, Root e HTTP/3'],correct:'AES-128-GCM, AES-256-GCM e ChaCha20-Poly1305',explanation:'São cifras autenticadas usadas para proteger dados da sessão.'},
  {id:'tls13-5',moduleId:'tls13',type:'mc',prompt:'HTTP/3 usa:',options:['QUIC sobre UDP com TLS 1.3 integrado','TCP com TLS 3','UDP sem criptografia','JKS sobre HTTP/2'],correct:'QUIC sobre UDP com TLS 1.3 integrado',explanation:'HTTP/3 não significa “TLS 3”.'}
];
