const fileIsoOSSData = [
"Sales document",
"Created by 'Item'",
"Created on 'Item'",
"Entry Time",
"Department number",
"Division",
"Requested Delivery Date Item",
"Purchase Order No.",
"Incoterms Item",
"Material",
"Material description",
"Customer Material number",
"Item Order Quantity",
"Sales Unit(UOM)",
"Delivery Block Code Item",
"Delivery Block Text Item",
"Reason for Rejection Code(Rj)",
"Reason for Rejection Code Desc",
"Ship With Text",
"Group",
"Plant",
"Plant Name1",
"Plant Street",
"Plant City",
"Plant Region",
"Plant Postal Code",
"Shipping Point",
"Shipping Point Desc",
"Customer-Headquarter number",
"HQ Name 1",
"HQ Name 2",
"Sold to party",
"Sold-To Name 1",
"Sold-To Name 2",
"Sold-To City",
"Sold-To Region",
"PO Type",
"Customer Ship-To",
"Ship to Name 1",
"Ship to Name 2",
"Ship to Street",
"Ship to City",
"Ship to Region state",
"Delivery Number",
"Shipment Document",
"Invoice Date",
"Shipping Condition",
"BOL",
"Goods Issue Date",
"PlnShipStrt",
"PlnShipEndD",
"PlnShpEndT",
"SCACD",
"PlnLdStart",
"PlnLdStrtT",
"PlnLdEndDt",
"PlnLdEndTim",
"ActLdEndDt",
"ActlLdEndTm",
"ActShpStrD",
"ActShpStrT",
"ActShpEndD",
"ActShpEndTime",
"Total Volume",
"Volume Unit",
"Net Weight",
"Weight Unit",
"Delivery Status",
"Equipment type",
"Item Order Quantity",
"Item Gross Weight",
"Item Net Price",
"Item Confirmed Quantity",
"Item Net Weight",
"Item Total Volume",
"Header Net Value",
"Header Total Volume",
"Header Gross Weight",
"Header Net Weight",
"Header Confirmed Gross Weight",
"Delivery Block Hdr Desc",
"Sales Order Agreement",
"Header Volume Confirmed Quantity",
"Original Order Quantity"
]

// Use to convert the fileIsoOSSData to json
// This was necessary to have an id when asking chatGPT to correlate the fields with api.
//
// let idCount = 3;
// let fileIsoOSSDataObj = fileIsoOSSData.map(item => {
//     return {
//         name: item,
//         id: idCount++
//     }
// })
