const fileIsoCustomerScoreCardData = [
    "Company Desc",
    "Sold To Desc",
    "Sold To",
    "Ship To Desc",
    "Material",
    "Customer material",
    "Material Desc",
    "Reason for Rejection",
    "Reason code & Desc",
    "Sales Document",
    "Customer PO number",
    "Period",
    "Sales Order Count",
    "On Time %",
    "Cust Ord Item Fill Qty",
    "Order Quantity",
    "Case Fill Rate fe",
    "Cube/Order",
    "Cube/Shipment",
    "Shipped Dollars",
    "Profit Business Unit Desc",
    "Year",
    "Week",
    "P&L Category Desc",
    "Product Level 1 Desc",
    "Shipment Document",
    "Has Ship End Date",
    "Shipping Type Desc",
    "Sales Document Type",
    "Plant",
    "PlantDesc",
    "Product Level 2 Desc",
    "No of Records"
];