const connectionsData = [
    { "from": { "name": "Sales document", "id": 3 }, "to": { "fieldName": "external_id", "id": 4001, "parent": "PurchaseOrder" } },
    { "from": { "name": "Created by 'Item'", "id": 4 }, "to": { "fieldName": "business_entity_id", "id": 5015, "parent": "Shipment.legs.start.tasks" } },
    { "from": { "name": "Created on 'Item'", "id": 5 }, "to": { "fieldName": "placed_at", "id": 4004, "parent": "PurchaseOrder" } },
    { "from": { "name": "Entry Time", "id": 6 }, "to": { "fieldName": "arrived_at", "id": 5029, "parent": "Shipment.legs.start" } },
    { "from": { "name": "Department number", "id": 7 }, "to": { "fieldName": "external_id", "id": 2001, "parent": "Facility" } },
    { "from": { "name": "Division", "id": 8 }, "to": { "fieldName": "business_entity_type", "id": 2004, "parent": "Facility" } },
    { "from": { "name": "Requested Delivery Date Item", "id": 9 }, "to": { "fieldName": "requested_delivery_date", "id": 5088, "parent": "Shipment" } },
    { "from": { "name": "Purchase Order No.", "id": 10 }, "to": { "fieldName": "external_id", "id": 4001, "parent": "PurchaseOrder" } },
    { "from": { "name": "Incoterms Item", "id": 11 }, "to": { "fieldName": "value_currency_code", "id": 4010, "parent": "PurchaseOrder" } },
    { "from": { "name": "Material", "id": 12 }, "to": { "fieldName": "material_description", "id": 4013, "parent": "PurchaseOrder" } },
    { "from": { "name": "Material description", "id": 13 }, "to": { "fieldName": "material_description", "id": 4013, "parent": "PurchaseOrder" } },
    { "from": { "name": "Customer Material number", "id": 14 }, "to": { "fieldName": "customer_material_number", "id": 4012, "parent": "PurchaseOrder" } },
    { "from": { "name": "Item Order Quantity", "id": 15 }, "to": { "fieldName": "shipped_quantity", "id": 4008, "parent": "PurchaseOrder" } },
    { "from": { "name": "Sales Unit(UOM)", "id": 16 }, "to": { "fieldName": "unit_type", "id": 4006, "parent": "PurchaseOrder" } },
    { "from": { "name": "Delivery Block Code Item", "id": 17 }, "to": { "fieldName": "exception_type", "id": 5035, "parent": "Shipment.legs.start.reason_codes" } },
    { "from": { "name": "Delivery Block Text Item", "id": 18 }, "to": { "fieldName": "reason_code", "id": 5036, "parent": "Shipment.legs.start.reason_codes" } },
    { "from": { "name": "Reason for Rejection Code(Rj)", "id": 19 }, "to": { "fieldName": "exception_type", "id": 5065, "parent": "Shipment.legs.end.reason_codes" } },
    { "from": { "name": "Reason for Rejection Code Desc", "id": 20 }, "to": { "fieldName": "code", "id": 5066, "parent": "Shipment.legs.end.reason_codes" } },
    { "from": { "name": "Ship With Text", "id": 21 }, "to": { "fieldName": "fulfillment_type", "id": 5018, "parent": "Shipment.legs.start.tasks" } },
    { "from": { "name": "Group", "id": 22 }, "to": { "fieldName": "business_name", "id": 1002, "parent": "Consignee" } },
    { "from": { "name": "Plant", "id": 23 }, "to": { "fieldName": "facility_id", "id": 5042, "parent": "Shipment.legs.end" } },
    { "from": { "name": "Plant Name1", "id": 24 }, "to": { "fieldName": "facility_name", "id": 5013, "parent": "Shipment.legs.start" } },
    { "from": { "name": "Plant Street", "id": 25 }, "to": { "fieldName": "domicile_address_1", "id": 1003, "parent": "Consignee" } },
    { "from": { "name": "Plant City", "id": 26 }, "to": { "fieldName": "domicile_city", "id": 1005, "parent": "Consignee" } },
    { "from": { "name": "Plant Region", "id": 27 }, "to": { "fieldName": "domicile_principle_subdivision", "id": 1006, "parent": "Consignee" } },
    { "from": { "name": "Plant Postal Code", "id": 28 }, "to": { "fieldName": "domicile_postal_code", "id": 1008, "parent": "Consignee" } },
    { "from": { "name": "Shipping Point", "id": 29 }, "to": { "fieldName": "shipping_point", "id": 5076, "parent": "Shipment" } },
    { "from": { "name": "Shipping Point Name", "id": 30 }, "to": { "fieldName": "name", "id": 2002, "parent": "Facility" } },
    { "from": { "name": "Shipping Point Street", "id": 31 }, "to": { "fieldName": "raw_address", "id": 2005, "parent": "Facility" } },
    { "from": { "name": "Shipping Point City", "id": 32 }, "to": { "fieldName": "domicile_city", "id": 1005, "parent": "Consignee" } },
    { "from": { "name": "Shipping Point Region", "id": 33 }, "to": { "fieldName": "domicile_principle_subdivision", "id": 1006, "parent": "Consignee" } },
    { "from": { "name": "Shipping Point Postal Code", "id": 34 }, "to": { "fieldName": "domicile_postal_code", "id": 1008, "parent": "Consignee" } }
]