export const STUDENT_NAME = "João Lucas Fabiano";

export const CONFIG = {
  studentAge: 9,
  grade: "4º ano EF",
  subject: "Matemática",
  examDate: null,
  questionsPerRound: 8,
  vfPerRound: 0,
  passScore: 7,
  streakRequired: 3,
  maxHearts: 3,
};

export const BASE_QUESTIONS = [
  // —— Modelo 1: multiplicação ——
  {
    id: "m1-q1a",
    tema: "Tabuada",
    questionText: "7 × 4 = ?",
    options: ["28", "24", "32", "35"],
    correctOptionIndex: 0,
    explicacao: "7 × 4 = 28. Você pode somar 7 quatro vezes ou usar a tabuada do 7.",
  },
  {
    id: "m1-q1b",
    tema: "Tabuada",
    questionText: "8 × 6 = ?",
    options: ["48", "42", "54", "56"],
    correctOptionIndex: 0,
    explicacao: "8 × 6 = 48.",
  },
  {
    id: "m1-q1c",
    tema: "Tabuada",
    questionText: "9 × 3 = ?",
    options: ["27", "24", "30", "33"],
    correctOptionIndex: 0,
    explicacao: "9 × 3 = 27.",
  },
  {
    id: "m1-q1d",
    tema: "Tabuada",
    questionText: "5 × 7 = ?",
    options: ["35", "30", "40", "42"],
    correctOptionIndex: 0,
    explicacao: "5 × 7 = 35.",
  },
  {
    id: "m1-q2a",
    tema: "Multiplicação",
    questionText: "12 × 3 = ?",
    options: ["36", "33", "39", "42"],
    correctOptionIndex: 0,
    explicacao: "12 × 3 = 36. Pense: 10 × 3 = 30 e 2 × 3 = 6, então 30 + 6 = 36.",
  },
  {
    id: "m1-q2b",
    tema: "Multiplicação",
    questionText: "15 × 4 = ?",
    options: ["60", "55", "65", "50"],
    correctOptionIndex: 0,
    explicacao: "15 × 4 = 60.",
  },
  {
    id: "m1-q2c",
    tema: "Multiplicação",
    questionText: "21 × 2 = ?",
    options: ["42", "40", "44", "38"],
    correctOptionIndex: 0,
    explicacao: "21 × 2 = 42.",
  },
  {
    id: "m1-q2d",
    tema: "Multiplicação",
    questionText: "13 × 5 = ?",
    options: ["65", "60", "70", "55"],
    correctOptionIndex: 0,
    explicacao: "13 × 5 = 65.",
  },
  {
    id: "m1-q3a",
    tema: "Três fatores",
    questionText: "2 × 3 × 4 = ?",
    options: ["24", "20", "28", "18"],
    correctOptionIndex: 0,
    explicacao: "Primeiro 2 × 3 = 6, depois 6 × 4 = 24.",
  },
  {
    id: "m1-q3b",
    tema: "Três fatores",
    questionText: "5 × 2 × 6 = ?",
    options: ["60", "50", "55", "70"],
    correctOptionIndex: 0,
    explicacao: "5 × 2 = 10 e 10 × 6 = 60.",
  },
  {
    id: "m1-q3c",
    tema: "Três fatores",
    questionText: "3 × 4 × 5 = ?",
    options: ["60", "55", "65", "50"],
    correctOptionIndex: 0,
    explicacao: "3 × 4 = 12 e 12 × 5 = 60.",
  },
  {
    id: "m1-q4a",
    tema: "× 10, 100 e 1000",
    questionText: "25 × 10 = ?",
    options: ["250", "25", "2500", "205"],
    correctOptionIndex: 0,
    explicacao: "Multiplicar por 10 acrescenta um zero: 25 × 10 = 250.",
  },
  {
    id: "m1-q4b",
    tema: "× 10, 100 e 1000",
    questionText: "34 × 100 = ?",
    options: ["3400", "340", "34000", "3040"],
    correctOptionIndex: 0,
    explicacao: "Multiplicar por 100 acrescenta dois zeros: 34 × 100 = 3400.",
  },
  {
    id: "m1-q4c",
    tema: "× 10, 100 e 1000",
    questionText: "7 × 1000 = ?",
    options: ["7000", "700", "70000", "70"],
    correctOptionIndex: 0,
    explicacao: "7 × 1000 = 7000.",
  },
  {
    id: "m1-q4d",
    tema: "× 10, 100 e 1000",
    questionText: "56 × 10 = ?",
    options: ["560", "56", "5600", "506"],
    correctOptionIndex: 0,
    explicacao: "56 × 10 = 560.",
  },
  {
    id: "m1-q6a",
    tema: "Mais algarismos",
    questionText: "23 × 4 = ?",
    options: ["92", "84", "96", "88"],
    correctOptionIndex: 0,
    explicacao: "23 × 4 = 92.",
  },
  {
    id: "m1-q6b",
    tema: "Mais algarismos",
    questionText: "32 × 3 = ?",
    options: ["96", "90", "99", "93"],
    correctOptionIndex: 0,
    explicacao: "32 × 3 = 96.",
  },
  {
    id: "m1-q6c",
    tema: "Mais algarismos",
    questionText: "14 × 6 = ?",
    options: ["84", "78", "90", "72"],
    correctOptionIndex: 0,
    explicacao: "14 × 6 = 84.",
  },
  {
    id: "m1-q7",
    tema: "Problema",
    questionText:
      "Uma professora organizou 6 fileiras com 8 alunos em cada uma. Quantos alunos havia ao todo?",
    options: ["48 alunos", "42 alunos", "54 alunos", "56 alunos"],
    correctOptionIndex: 0,
    explicacao: "6 × 8 = 48 alunos.",
  },
  {
    id: "m1-q8",
    tema: "Problema",
    questionText:
      "Em uma caixa há 9 pacotes com 5 figurinhas em cada pacote. Quantas figurinhas há ao todo?",
    options: ["45 figurinhas", "40 figurinhas", "50 figurinhas", "54 figurinhas"],
    correctOptionIndex: 0,
    explicacao: "9 × 5 = 45 figurinhas.",
  },
  {
    id: "m1-q9",
    tema: "Problema",
    questionText:
      "Uma floricultura recebeu 4 caixas com 25 rosas em cada caixa. Quantas rosas recebeu?",
    options: ["100 rosas", "90 rosas", "110 rosas", "75 rosas"],
    correctOptionIndex: 0,
    explicacao: "4 × 25 = 100 rosas.",
  },
  {
    id: "m1-q10",
    tema: "Possibilidades",
    questionText: "Qual multiplicação abaixo tem resultado 24?",
    options: ["4 × 6", "3 × 7", "5 × 5", "8 × 4"],
    correctOptionIndex: 0,
    explicacao:
      "4 × 6 = 24. Outras possibilidades: 1×24, 2×12, 3×8.",
  },

  // —— Modelo 2: quatro operações ——
  {
    id: "m2-q11a",
    tema: "Adição",
    questionText: "348 + 125 = ?",
    options: ["473", "463", "483", "453"],
    correctOptionIndex: 0,
    explicacao: "348 + 125 = 473.",
  },
  {
    id: "m2-q11b",
    tema: "Subtração",
    questionText: "762 − 248 = ?",
    options: ["514", "524", "504", "494"],
    correctOptionIndex: 0,
    explicacao: "762 − 248 = 514.",
  },
  {
    id: "m2-q12a",
    tema: "Divisão",
    questionText: "36 ÷ 4 = ?",
    options: ["9", "8", "7", "10"],
    correctOptionIndex: 0,
    explicacao: "36 ÷ 4 = 9.",
  },
  {
    id: "m2-q12b",
    tema: "Divisão",
    questionText: "42 ÷ 6 = ?",
    options: ["7", "6", "8", "9"],
    correctOptionIndex: 0,
    explicacao: "42 ÷ 6 = 7.",
  },
  {
    id: "m2-q12c",
    tema: "Divisão",
    questionText: "56 ÷ 8 = ?",
    options: ["7", "6", "8", "9"],
    correctOptionIndex: 0,
    explicacao: "56 ÷ 8 = 7.",
  },
  {
    id: "m2-q13",
    tema: "Problema",
    questionText:
      "Uma escola comprou 48 lápis para distribuir igualmente entre 6 alunos. Quantos lápis cada aluno recebeu?",
    options: ["8 lápis", "7 lápis", "9 lápis", "6 lápis"],
    correctOptionIndex: 0,
    explicacao: "48 ÷ 6 = 8 lápis para cada aluno.",
  },
  {
    id: "m2-q14",
    tema: "Problema",
    questionText:
      "Pedro tinha 75 bolinhas de gude. Deu 28 para seu primo. Com quantas bolinhas ficou?",
    options: ["47 bolinhas", "43 bolinhas", "53 bolinhas", "57 bolinhas"],
    correctOptionIndex: 0,
    explicacao: "75 − 28 = 47 bolinhas.",
  },
  {
    id: "m2-q15",
    tema: "Problema",
    questionText:
      "Uma papelaria vendeu 8 caixas com 12 lápis cada uma e mais 15 lápis avulsos. Quantos lápis foram vendidos?",
    options: ["111 lápis", "96 lápis", "105 lápis", "120 lápis"],
    correctOptionIndex: 0,
    explicacao: "8 × 12 = 96, depois 96 + 15 = 111 lápis.",
  },
  {
    id: "m2-q16",
    tema: "Tabuada do 7",
    questionText: "7 × 5 = ?",
    options: ["35", "30", "42", "28"],
    correctOptionIndex: 0,
    explicacao: "7 × 5 = 35.",
  },
  {
    id: "m2-q17",
    tema: "Problema",
    questionText:
      "Um estacionamento possui 15 fileiras com 10 carros em cada uma. Quantos carros há estacionados?",
    options: ["150 carros", "140 carros", "160 carros", "105 carros"],
    correctOptionIndex: 0,
    explicacao: "15 × 10 = 150 carros.",
  },
  {
    id: "m2-q18",
    tema: "Três fatores",
    questionText:
      "Uma fábrica organizou 3 caixas. Em cada caixa há 4 pacotes, e cada pacote contém 5 balas. Quantas balas há ao todo?",
    options: ["60 balas", "50 balas", "70 balas", "45 balas"],
    correctOptionIndex: 0,
    explicacao: "3 × 4 × 5 = 60 balas.",
  },
  {
    id: "m2-q19a",
    tema: "× 10, 100 e 1000",
    questionText: "125 × 10 = ?",
    options: ["1250", "125", "12500", "1125"],
    correctOptionIndex: 0,
    explicacao: "125 × 10 = 1250.",
  },
  {
    id: "m2-q19b",
    tema: "× 10, 100 e 1000",
    questionText: "48 × 100 = ?",
    options: ["4800", "480", "48000", "4080"],
    correctOptionIndex: 0,
    explicacao: "48 × 100 = 4800.",
  },
  {
    id: "m2-q19c",
    tema: "× 10, 100 e 1000",
    questionText: "9 × 1000 = ?",
    options: ["9000", "900", "90000", "90"],
    correctOptionIndex: 0,
    explicacao: "9 × 1000 = 9000.",
  },
  {
    id: "m2-q20",
    tema: "Desafio",
    questionText:
      "Em uma fazenda há 8 galinheiros com 12 galinhas em cada um. Se nasceram mais 16 pintinhos, quantas aves há agora?",
    options: ["112 aves", "96 aves", "108 aves", "104 aves"],
    correctOptionIndex: 0,
    explicacao: "8 × 12 = 96 galinhas, depois 96 + 16 = 112 aves.",
  },
];

/** Prova impressa — espelha prova.txt (questões 1–20) */
export const PRINT_EXAM_QUESTIONS = [
  {
    number: 1,
    title: "Complete as multiplicações:",
    type: "subitems",
    subitems: [
      { label: "a", text: "7 × 4 = ____", answer: "28" },
      { label: "b", text: "8 × 6 = ____", answer: "48" },
      { label: "c", text: "9 × 3 = ____", answer: "27" },
      { label: "d", text: "5 × 7 = ____", answer: "35" },
    ],
  },
  {
    number: 2,
    title: "Resolva:",
    type: "subitems",
    subitems: [
      { label: "a", text: "12 × 3 = ____", answer: "36" },
      { label: "b", text: "15 × 4 = ____", answer: "60" },
      { label: "c", text: "21 × 2 = ____", answer: "42" },
      { label: "d", text: "13 × 5 = ____", answer: "65" },
    ],
  },
  {
    number: 3,
    title: "Multiplicação com três fatores:",
    type: "subitems",
    subitems: [
      { label: "a", text: "2 × 3 × 4 = ____", answer: "24" },
      { label: "b", text: "5 × 2 × 6 = ____", answer: "60" },
      { label: "c", text: "3 × 4 × 5 = ____", answer: "60" },
    ],
  },
  {
    number: 4,
    title: "Multiplicando por 10, 100 e 1000:",
    type: "subitems",
    subitems: [
      { label: "a", text: "25 × 10 = ____", answer: "250" },
      { label: "b", text: "34 × 100 = ____", answer: "3400" },
      { label: "c", text: "7 × 1000 = ____", answer: "7000" },
      { label: "d", text: "56 × 10 = ____", answer: "560" },
    ],
  },
  {
    number: 5,
    title: "Escreva duas maneiras diferentes de resolver:",
    type: "open",
    text: "8 × 5 = ____\n(Explique ou desenhe sua estratégia.)",
    answer:
      "40. Exemplos: somar 8 cinco vezes (8+8+8+8+8) ou somar 5 oito vezes (5+5+5+5+5+5+5+5), ou usar a tabuada.",
    lines: 4,
  },
  {
    number: 6,
    title: "Resolva as multiplicações:",
    type: "subitems",
    subitems: [
      { label: "a", text: "23 × 4 = ____", answer: "92" },
      { label: "b", text: "32 × 3 = ____", answer: "96" },
      { label: "c", text: "14 × 6 = ____", answer: "84" },
    ],
  },
  {
    number: 7,
    type: "problem",
    text: "Uma professora organizou 6 fileiras com 8 alunos em cada uma. Quantos alunos havia ao todo?",
    answer: "48 alunos",
  },
  {
    number: 8,
    type: "problem",
    text: "Em uma caixa há 9 pacotes com 5 figurinhas em cada pacote. Quantas figurinhas há ao todo?",
    answer: "45 figurinhas",
  },
  {
    number: 9,
    type: "problem",
    text: "Uma floricultura recebeu 4 caixas com 25 rosas em cada caixa. Quantas rosas recebeu?",
    answer: "100 rosas",
  },
  {
    number: 10,
    type: "open",
    title: "Possibilidades",
    text: "De quantas maneiras diferentes podemos formar o número 24 usando uma multiplicação?\nEscreva pelo menos 4 possibilidades.",
    answer: "Exemplos: 1×24, 2×12, 3×8, 4×6",
    lines: 5,
  },
  {
    number: 11,
    title: "Resolva as operações:",
    type: "subitems",
    subitems: [
      { label: "a", text: "348 + 125 = ____", answer: "473" },
      { label: "b", text: "762 − 248 = ____", answer: "514" },
    ],
  },
  {
    number: 12,
    title: "Resolva:",
    type: "subitems",
    subitems: [
      { label: "a", text: "36 ÷ 4 = ____", answer: "9" },
      { label: "b", text: "42 ÷ 6 = ____", answer: "7" },
      { label: "c", text: "56 ÷ 8 = ____", answer: "7" },
    ],
  },
  {
    number: 13,
    type: "problem",
    text: "Uma escola comprou 48 lápis para distribuir igualmente entre 6 alunos. Quantos lápis cada aluno recebeu?",
    answer: "8 lápis",
  },
  {
    number: 14,
    type: "problem",
    text: "Pedro tinha 75 bolinhas de gude. Deu 28 para seu primo. Com quantas bolinhas ficou?",
    answer: "47 bolinhas",
  },
  {
    number: 15,
    type: "problem",
    title: "Problema envolvendo multiplicação e adição",
    text: "Uma papelaria vendeu 8 caixas com 12 lápis cada uma e mais 15 lápis avulsos. Quantos lápis foram vendidos?",
    answer: "111 lápis",
  },
  {
    number: 16,
    title: "Complete a tabuada do 7:",
    type: "subitems",
    subitems: [
      { label: "", text: "7 × 1 = ____", answer: "7" },
      { label: "", text: "7 × 2 = ____", answer: "14" },
      { label: "", text: "7 × 3 = ____", answer: "21" },
      { label: "", text: "7 × 4 = ____", answer: "28" },
      { label: "", text: "7 × 5 = ____", answer: "35" },
      { label: "", text: "7 × 6 = ____", answer: "42" },
    ],
  },
  {
    number: 17,
    type: "problem",
    text: "Um estacionamento possui 15 fileiras com 10 carros em cada uma. Quantos carros há estacionados?",
    answer: "150 carros",
  },
  {
    number: 18,
    type: "problem",
    title: "Problema com três fatores",
    text: "Uma fábrica organizou 3 caixas. Em cada caixa há 4 pacotes, e cada pacote contém 5 balas.\nQuantas balas há ao todo?",
    answer: "60 balas",
  },
  {
    number: 19,
    title: "Resolva:",
    type: "subitems",
    subitems: [
      { label: "a", text: "125 × 10 = ____", answer: "1250" },
      { label: "b", text: "48 × 100 = ____", answer: "4800" },
      { label: "c", text: "9 × 1000 = ____", answer: "9000" },
    ],
  },
  {
    number: 20,
    type: "problem",
    title: "Desafio",
    text: "Em uma fazenda há 8 galinheiros com 12 galinhas em cada um. Se nasceram mais 16 pintinhos, quantas aves há agora?",
    answer: "112 aves",
  },
];

export function getPrintQuestionsByModel(modelNumber) {
  if (modelNumber === 1) return PRINT_EXAM_QUESTIONS.slice(0, 10);
  if (modelNumber === 2) return PRINT_EXAM_QUESTIONS.slice(10, 20);
  return PRINT_EXAM_QUESTIONS.slice();
}
